plugins {
	id 'org.springframework.boot' version '3.2.2'
	id 'io.spring.dependency-management' version '1.1.4'
	id 'java'
	id "org.sonarqube" version "6.2.0.5505"
}
sonar {
	properties {
		property "sonar.projectKey", "release-insights"
		property "sonar.projectName", "release-insights"
	}
}
group = 'com.example'
version = '1.0.0'
sourceCompatibility = '21'
repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/snapshot' }
	maven { url 'https://repo.spring.io/milestone' }
}
ext {
	set('springAiVersion', "1.0.0-M4")
}
subprojects {
	apply plugin: 'java'
	group = 'com.example'
	version = '1.0.0'
}
dependencies {
	// Spring Boot Web for REST API
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Spring Boot Scheduler (for @Scheduled jobs)
	implementation 'org.springframework.boot:spring-boot-starter'

	// GitHub API client
	implementation 'org.kohsuke:github-api:1.315'

	implementation 'org.springframework.ai:spring-ai-vertex-ai-gemini-spring-boot-starter:1.0.0-M4'

	// Jackson for JSON processing
	implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'

	// JSON library
	implementation 'org.json:json:20230618'

	// Lombok (optional, for reducing boilerplate code)
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Spring Boot Test (optional, for unit testing)
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'com.intuit.karate:karate-junit5:1.4.1'
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
	}
}

tasks.named('test') {
	useJUnitPlatform()
}