name: Release Build

on:
  push:
    branches:
      - 'release/**'
  create:
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  analyze-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set execute permissions
        run: chmod +x ./scripts/release_analysis.sh

      - name: Run Release Analysis
        run: ./scripts/release_analysis.sh
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Prepare HTML Table
        id: prepare_table
        run: |
          summary_table="<table border='1'><tr><th>File</th><th>Summary</th></tr>"
          printenv | grep '^summary_map_' | sed 's/^summary_map_//' | while IFS='=' read -r file summary; do
            echo "Processing file: $file with summary: $summary"  # Debugging line
            summary_table+="<tr><td>${file}</td><td>${summary}</td></tr>"
          done
          summary_table+="</table>"
          echo "::set-output name=summary_table::${summary_table}"

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: Release Summary
          to: sireesha.malla@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          content_type: text/html
          body: ${{ steps.prepare_table.outputs.summary_table }}