name: Release Build

on:
  push:
    branches:
      - 'release/**'
  create:
    branches:
      - 'release/**'
  workflow_dispatch:

jobs:
  analyze-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set execute permissions
        run: chmod +x ./scripts/release_analysis.sh ./scripts/fetch_jira_stories.sh ./scripts/call_gemini_stories_summary.sh ./scripts/call_gemini.sh

      - name: Run Release Analysis
        run: ./scripts/release_analysis.sh
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Fetch Jira Stories for Latest Branch
        run: ./scripts/fetch_jira_stories.sh
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_DOMAIN: sirimalla102.atlassian.net
          BOARD_ID: 34
          FIX_VERSION: release-25.69
      - name: Call Gemini AI
        id: call_gemini
        run: ./scripts/call_gemini_stories_summary.sh
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          STORY_TABLE: ${{ steps.fetch_stories.outputs.html_table }}

      - name: Prepare HTML Table
        id: prepare_table
        run: |
          summary_table="<table border='1'><tr><th>File</th><th>Summary</th></tr>"
          while IFS='=' read -r fisle summary; do
            echo "Processing file: $file with summary: $summary"  # Debugging line
            summary_table="${summary_table}<tr><td>${file}</td><td>${summary}</td></tr>"
            echo "Current summary_table: ${summary_table}"  # Debugging line
          done < <(printenv | grep '^summary_map_' | sed 's/^summary_map_//')
          summary_table="${summary_table}</table>"
          echo "Summary Table: ${summary_table}"  # Print the summary table
          echo "::set-output name=summary_table::${summary_table}"

      - name: Call Gemini AI
        id: call_gemini
        run: ./scripts/call_gemini.sh
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUMMARY_TABLE: ${{ steps.prepare_table.outputs.summary_table }}

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: Release Summary
          to: sireesha.malla@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          content_type: text/html
          html_body: |
            <h2>Gemini Jira Story Summary</h2>
            <p>${{ steps.call_gemini.outputs.gemini_stories_summary }}</p>
            <h2>Jira Story Details</h2>
            ${{ steps.fetch_stories.outputs.html_table }}
            <h2>Gemini code changes Summary</h2>
            <p>${{ steps.call_gemini.outputs.gemini_summary }}</p>
            <h2>Code Changes Details</h2>
            ${{ steps.prepare_table.outputs.summary_table }}